---
title: "GBM_example"
author: "Travis Johnson"
date: "10/3/2021"
output: md_document
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r, max.height='100px', attr.output='.numberLines'}
library(DEGAS)
library(Rtsne)
library(ggplot2)
```

# Load data
```{r, max.height='100px', attr.output='.numberLines'}
scDat = read.csv('scDat.csv',row.names=1)
patDat = read.csv('patDat.csv',row.names=1)
patLab = read.csv('patLab.csv',row.names=1)
```

# Initialize DEGAS framework
```{r, max.height='100px', attr.output='.numberLines'}
path.data = ''
path.result = ''
initDEGAS()
set_seed_term(2)
tmpDir = 'tmp/'
```

# Training DEGAS model
```{r, max.height='100px', attr.output='.numberLines'}
ccModel1 = runCCMTLBag(scDat,NULL,patDat,patLab,tmpDir,'BlankClass','DenseNet',3,5)
```

# Predictions from DEGAS model
```{r, max.height='100px', attr.output='.numberLines'}
# Predicting patient outcome in cells
# ie, predicting GBM subtype association in individual cells
scpatPreds = predClassBag(ccModel1,scDat,'pat')
colnames(scpatPreds) = colnames(patLab)
```

# Displaying single cells overlaid with GBM subtype impressions
```{r, max.height='100px', attr.output='.numberLines'}
# Set seed and run tSNE
set.seed(1)
scDat_tsne = Rtsne(scDat)
colnames(scDat_tsne$Y) = c('tSNE1','tSNE2')
# kNN smoothing of GBM subtype association
impressions_sc_smooth = knnSmooth(scpatPreds,scDat_tsne$Y)
# Conversion of GBM subtype association to correlation
impressions_sc_smooth_cor = toCorrCoeff(impressions_sc_smooth)
tmp = data.frame(tSNE1=scDat_tsne$Y[,"tSNE1"],tSNE2=scDat_tsne$Y[,"tSNE2"],
                 Proneural=impressions_sc_smooth_cor[,"Proneural"],
                 Neural=impressions_sc_smooth_cor[,"Neural"],
                 Classical=impressions_sc_smooth_cor[,"Classical"],
                 Mesenchymal=impressions_sc_smooth_cor[,"Mesenchymal"],
                 Patient=sub("[_].*","",rownames(scDat)))
# Mesenchymal
p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=Mesenchymal,shape=Patient))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Mesenchymal\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))
# Proneural
p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=Proneural,shape=Patient))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Proneural\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))
# Neural
p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=Neural,shape=Patient))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Neural\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))
# Classical
p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=Classical,shape=Patient))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Classical\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))

```

# Session Info
```{r, max.height='100px', attr.output='.numberLines'}
sessionInfo()
```


