---
title: "Sim_example"
author: "Travis Johnson"
date: "10/04/2021"
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load required packages
```{r, max.height='100px', attr.output='.numberLines'}
library(DEGAS)
library(Rtsne)
library(ggplot2)
```

# Load data
```{r, max.height='100px', attr.output='.numberLines'}
scDat = read.csv('scDat.csv',row.names=1)
scLab = read.csv('scLab.csv',row.names=1)
patDatSim1 = read.csv('patDatSim1.csv',row.names=1)
patDatSim2 = read.csv('patDatSim2.csv',row.names=1)
patDatSim3 = read.csv('patDatSim3.csv',row.names=1)
patLab = read.csv('patLab.csv',row.names=1)
```

# Initialize DEGAS framework
```{r, max.height='100px', attr.output='.numberLines'}
path.data = ''
path.result = ''
initDEGAS()
set_seed_term(2)
tmpDir = paste0(path.result, 'tmp/')
```

# Training DEGAS models for each simulation
```{r, max.height='100px', attr.output='.numberLines'}
ccModelSim1 = runCCMTLBag(scDat,scLab,patDatSim1,patLab,tmpDir,'ClassClass','DenseNet',3,5)
ccModelSim2 = runCCMTLBag(scDat,scLab,patDatSim2,patLab,tmpDir,'ClassClass','DenseNet',3,5)
ccModelSim3 = runCCMTLBag(scDat,scLab,patDatSim3,patLab,tmpDir,'ClassClass','DenseNet',3,5)
```

# Predictions from DEGAS model for each simulation
```{r, max.height='100px', attr.output='.numberLines'}
# Predicting patient outcome in cells
# ie, predicting AD association in individual cells
scpatPredsSim1 = predClassBag(ccModelSim1,scDat,'pat')
colnames(scpatPredsSim1) = colnames(patLab)
scpatPredsSim2 = predClassBag(ccModelSim2,scDat,'pat')
colnames(scpatPredsSim2) = colnames(patLab)
scpatPredsSim3 = predClassBag(ccModelSim3,scDat,'pat')
colnames(scpatPredsSim3) = colnames(patLab)
```

# Displaying single cells overlaid with AD impressions
```{r, max.height='100px', attr.output='.numberLines'}
# Set seed and run tSNE
set.seed(1)
scDat_tsne = Rtsne(scDat,initial_dims=4)
colnames(scDat_tsne$Y) = c('tSNE1','tSNE2')
# kNN smoothing of disease association
impressions_sc_smooth_sim1 = knnSmooth(scpatPredsSim1[,"D"],scDat_tsne$Y)
impressions_sc_smooth_sim2 = knnSmooth(scpatPredsSim2[,"D"],scDat_tsne$Y)
impressions_sc_smooth_sim3 = knnSmooth(scpatPredsSim3[,"D"],scDat_tsne$Y)
# Conversion of disease association to correlation
impressions_sc_smooth_cor_sim1 = toCorrCoeff(impressions_sc_smooth_sim1)
impressions_sc_smooth_cor_sim2 = toCorrCoeff(impressions_sc_smooth_sim2)
impressions_sc_smooth_cor_sim3 = toCorrCoeff(impressions_sc_smooth_sim3)
tmp = data.frame(tSNE1=scDat_tsne$Y[,"tSNE1"],tSNE2=scDat_tsne$Y[,"tSNE2"],
                 DisSim1=impressions_sc_smooth_cor_sim1,
                 DisSim2=impressions_sc_smooth_cor_sim2,
                 DisSim3=impressions_sc_smooth_cor_sim3,
                 CT=fromOneHot(scLab))
# Plotting disease assoiations for simulaiton 1
p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=DisSim1,shape=CT))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Disease\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))

p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=DisSim2,shape=CT))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Disease\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))

p = ggplot(tmp,aes(x=tSNE1,y=tSNE2,color=DisSim3,shape=CT))+ geom_point() + 
          scale_color_gradient2(low = "black",mid="lavender",high="red")
plot(p+labs(color='Disease\nassociation',shape='Cell type') +
       theme(legend.title=element_text(size=rel(1)),
             legend.text=element_text(size=rel(1)),
             axis.title=element_text(size=rel(1)),
             axis.text.x=element_text(size=rel(1)),
             axis.text.y=element_text(size=rel(1))))


```

# Session Info
```{r, max.height='100px', attr.output='.numberLines'}
sessionInfo()
```









